# Generated by Django 4.2.15 on 2024-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='dryingmashine',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='foldingtable',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='washingmashine',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
