# Generated by Django 4.2.15 on 2024-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryingmashine',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_IN_USE', 'Not in Use'), ('Working', 'Working')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='washingmashine',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_IN_USE', 'Not in Use'), ('Working', 'Working')], max_length=100, null=True),
        ),
    ]
