# Generated by Django 4.2.15 on 2024-08-22 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_campus_isactive_alter_collection_isactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdaysheet',
            old_name='regular_cloths',
            new_name='campus_regular_cloths',
        ),
        migrations.RenameField(
            model_name='studentdaysheet',
            old_name='uniforms',
            new_name='campus_uniforms',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='college',
        ),
        migrations.AddField(
            model_name='faculty',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='college.campus'),
        ),
        migrations.AddField(
            model_name='facultydaysheet',
            name='delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='facultydaysheet',
            name='ware_house_regular_cloths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentdaysheet',
            name='delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentdaysheet',
            name='ware_house_regular_cloths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentdaysheet',
            name='ware_house_uniform',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
