# Generated by Django 4.2.15 on 2024-08-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_rename_regular_cloths_studentdaysheet_campus_regular_cloths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='max_student_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
