# Generated by Django 4.2.15 on 2024-08-27 17:05

import college.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_collection_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='logisticBagNumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_in_truck_image',
            new_name='campus_drop_collection_image',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_in_warehouse_image',
            new_name='campus_pickup_collection_image',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='drop_in_campus_image',
            new_name='warehouse_drop_image',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_while_dropping_in_truck',
            new_name='warehouse_pickup_image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='faculty_cloths_in_campus_image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='faculty_cloths_in_warehouse_image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='pickup_collection_image',
        ),
        migrations.RemoveField(
            model_name='facultydaysheet',
            name='tag_number',
        ),
        migrations.AddField(
            model_name='facultydaysheet',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.faculty'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='current_status',
            field=models.CharField(blank=True, choices=[('READY_TO_PICK', 'READY_TO_PICK'), ('INTRANSIT_FROM_cAMPUS', 'INTRANSIT_FROM_cAMPUS'), ('DELIVERED_TO_WAREHOUSE', 'DELIVERED_TO_WAREHOUSE'), ('WASHING', 'WASHING'), ('WASHING_DONE', 'WASHING_DONE'), ('DRYING', 'DRYING'), ('DRYING_DONE', 'DRYING_DONE'), ('IN_SEGREGATION', 'IN_SEGREGATION'), ('SEGREGATION_DONE', 'SEGREGATION_DONE'), ('READY_FOR_DELIVERY', 'READY_FOR_DELIVERY'), ('INTRANSIT_FROM_WAREHOUSE', 'INTRANSIT_FROM_WAREHOUSE'), ('DELIVERED_TO_CAMPUS', 'DELIVERED_TO_CAMPUS'), ('DELIVERED_TO_STUDENT', 'DELIVERED_TO_STUDENT')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FacultybagNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bag', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=college.models.upload_location)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='campus_drop_bag_numbers',
            field=models.ManyToManyField(blank=True, related_name='campus_drop_collections', to='college.logisticbagnumer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='campus_drop_faculty_bag_number',
            field=models.ManyToManyField(blank=True, related_name='campus_drop_faculty_collections', to='college.facultybagnumbers'),
        ),
        migrations.AddField(
            model_name='collection',
            name='campus_pickup_bag_numbers',
            field=models.ManyToManyField(blank=True, related_name='campus_pickup_collections', to='college.logisticbagnumer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='campus_pickup_faculty_bag_number',
            field=models.ManyToManyField(blank=True, related_name='campus_pickup_faculty_collections', to='college.facultybagnumbers'),
        ),
        migrations.AddField(
            model_name='collection',
            name='warehouse_drop_bag_numbers',
            field=models.ManyToManyField(blank=True, related_name='warehouse_drop_collections', to='college.logisticbagnumer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='warehouse_drop_faculty_bag_number',
            field=models.ManyToManyField(blank=True, related_name='warehouse_drop_faculty_collections', to='college.facultybagnumbers'),
        ),
        migrations.AddField(
            model_name='collection',
            name='warehouse_pickup_bag_numbers',
            field=models.ManyToManyField(blank=True, related_name='warehouse_pickup_collections', to='college.logisticbagnumer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='warehouse_pickup_faculty_bag_number',
            field=models.ManyToManyField(blank=True, related_name='warehouse_pickup_faculty_collections', to='college.facultybagnumbers'),
        ),
    ]
