# Generated by Django 4.2.15 on 2024-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_alter_collection_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Campus_Employee', 'Campus_Employee'), ('Driver', 'Driver'), ('Washing', 'Washing'), ('Drying', 'Drying'), ('Segregation', 'Segregation')], max_length=20, null=True),
        ),
    ]
