# Generated by Django 4.2.15 on 2024-09-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_alter_employee_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviosStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='previous_status',
            field=models.ManyToManyField(blank=True, to='college.previosstatus'),
        ),
    ]
