# Generated by Django 4.2.15 on 2024-09-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_previosstatus_collection_previous_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreviosStatus',
            new_name='PreviousStatus',
        ),
    ]
