# Generated by Django 4.2.15 on 2024-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_alter_collection_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='current_status',
            field=models.CharField(blank=True, choices=[('READY_TO_PICK', 'READY_TO_PICK'), ('INTRANSIT_FROM_cAMPUS', 'INTRANSIT_FROM_cAMPUS'), ('DELIVERED_TO_WAREHOUSE', 'DELIVERED_TO_WAREHOUSE'), ('WASHING', 'WASHING'), ('WASHING_DONE', 'WASHING_DONE'), ('DRYING', 'DRYING'), ('DRYING_DONE', 'DRYING_DONE'), ('IN_SEGREGATION', 'IN_SEGREGATION'), ('READY_FOR_DELIVERY', 'READY_FOR_DELIVERY'), ('INTRANSIT_FROM_WAREHOUSE', 'INTRANSIT_FROM_WAREHOUSE'), ('DELIVERED_TO_CAMPUS', 'DELIVERED_TO_CAMPUS'), ('DELIVERED_TO_STUDENT', 'DELIVERED_TO_STUDENT')], max_length=100, null=True),
        ),
    ]
