# Generated by Django 4.2.15 on 2024-09-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_otherclothbagnumber_otherclothdaysheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentremark',
            name='remark_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='remark_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='resolution',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
