# Generated by Django 4.2.15 on 2024-09-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_studentremark_remark_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='college_supervisor',
        ),
    ]
